version: 2.1

aliases:
  - &install_yarn_version
    name: Install specific Yarn version
    command: |
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
      echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
  - &restore_yarn_cache
    name: Restore Yarn cache
    keys:
      - yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}
  - &save_yarn_cache
    name: Save Yarn cache
    key: yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
  - &run_yarn_install
    name: Install dependencies
    command: yarn install --frozen-lockfile
  - &restore_dist_folders
    name: Restore dist folders
    command: |
      set -exu

      mkdir -p packages/horizontal-slider-js/dist
      mkdir -p packages/horizontal-slider-react/dist
      mkdir -p packages/horizontal-slider-vdom/dist
      mkdir -p packages/horizontal-slider-theme/dist
      mkdir -p packages/highlight-vdom/dist
      mkdir -p packages/shared/dist

      cp -R /tmp/workspace/packages/horizontal-slider-js/dist packages/horizontal-slider-js/
      cp -R /tmp/workspace/packages/horizontal-slider-react/dist packages/horizontal-slider-react/
      cp -R /tmp/workspace/packages/horizontal-slider-vdom/dist packages/horizontal-slider-vdom/
      cp -R /tmp/workspace/packages/horizontal-slider-theme/dist packages/horizontal-slider-theme/
      cp -R /tmp/workspace/packages/highlight-vdom/dist packages/highlight-vdom/
      cp -R /tmp/workspace/packages/shared/dist packages/shared/

defaults: &defaults
  working_directory: ~/ui-components
  docker:
    - image: cimg/node:14.15.0

references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Move dist folders to workspace
          command: |
            set -exu

            mkdir -p /tmp/workspace/packages/horizontal-slider-js/dist
            mkdir -p /tmp/workspace/packages/horizontal-slider-react/dist
            mkdir -p /tmp/workspace/packages/horizontal-slider-vdom/dist
            mkdir -p /tmp/workspace/packages/horizontal-slider-theme/dist
            mkdir -p /tmp/workspace/packages/highlight-vdom/dist
            mkdir -p /tmp/workspace/packages/shared/dist

            cp -R packages/horizontal-slider-js/dist /tmp/workspace/packages/horizontal-slider-js
            cp -R packages/horizontal-slider-react/dist /tmp/workspace/packages/horizontal-slider-react
            cp -R packages/horizontal-slider-vdom/dist /tmp/workspace/packages/horizontal-slider-vdom
            cp -R packages/horizontal-slider-theme/dist /tmp/workspace/packages/horizontal-slider-theme
            cp -R packages/highlight-vdom/dist /tmp/workspace/packages/highlight-vdom
            cp -R packages/shared/dist /tmp/workspace/packages/shared

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages
  test_lint:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run: *restore_dist_folders
      - run:
          name: Linting
          command: yarn run lint
  test_types:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Type checking
          command: yarn run test:types
  test_types_no_jsx_implementation:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run:
          name: Remove React types
          command: |
            # This simulates @types/react and preact not being installed
            node -e "
              fs.writeFileSync(
                './package.json',
                JSON.stringify(
                  Object.assign(require('./package.json'), {
                    resolutions: { 
                      '@types/react': 'file:./scripts/empty-package',
                      'preact': 'file:./scripts/empty-package',
                    },
                  }),
                  null,
                  2
                )
              );
            "
            # not running the scripts, as they should not run for *-react
            yarn install --ignore-scripts
      - run:
          name: Type checking
          # Using build:types instead of test:types, as it's easier to run only the VDOM types
          command: yarn build:types --scope '@algolia/*-vdom'
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run: *restore_dist_folders
      - run:
          name: Unit tests
          command: yarn run test --maxWorkers=4
  test_size:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run: *restore_dist_folders
      - run:
          name: Test packages size
          command: yarn run test:size
  release:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run: *restore_dist_folders
      - run:
          name: Release if needed
          command: yarn run shipjs trigger

workflows:
  version: 2.1
  ci:
    jobs:
      - build
      - test_types
      - test_types_no_jsx_implementation
      - test_lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - test_size:
          requires:
            - build
      - release:
          requires:
            - test_unit
            - test_lint
            - test_types
            - test_size
            - build
          filters:
            branches:
              only: master
